import type { Billboard, Region, Vendor } from "./types";

export const regions: Region[] = [
  { id: "1", name: "Greater Accra" },
  { id: "2", name: "Ashanti" },
  { id: "3", name: "Western" },
  { id: "4", name: "Northern" },
  { id: "5", name: "Volta" },
];

export const billboards: Billboard[] = [
  {
    id: "bb-acc-001",
    title: "Spintex Road Digital Display",
    type: "Digital LED",
    size: "12m x 6m",
    regionId: "1",
    city: "Accra",
    address: "Spintex Road, near Flower Pot",
    latitude: 5.6179,
    longitude: -0.1185,
    pricePerMonth: 15000,
    trafficEstimate: 200000,
    visibilityScore: 9,
    isDigital: true,
    isActive: true,
    createdAt: "2023-10-01T12:00:00Z",
    imageUrl: "https://picsum.photos/seed/accra1/600/400",
  },
  {
    id: "bb-acc-002",
    title: "Accra Mall Unipole",
    type: "Unipole",
    size: "18m x 12m",
    regionId: "1",
    city: "Accra",
    address: "Tetteh Quarshie Interchange, close to Accra Mall",
    latitude: 5.6231,
    longitude: -0.1659,
    pricePerMonth: 12000,
    trafficEstimate: 180000,
    visibilityScore: 8,
    isDigital: false,
    isActive: true,
    createdAt: "2023-09-15T12:00:00Z",
    imageUrl: "https://picsum.photos/seed/accra2/600/400",
  },
  {
    id: "bb-kum-001",
    title: "Adum Gantry Billboard",
    type: "Gantry",
    size: "20m x 5m",
    regionId: "2",
    city: "Kumasi",
    address: "Adum, over the main commercial street",
    latitude: 6.6885,
    longitude: -1.6244,
    pricePerMonth: 9000,
    trafficEstimate: 150000,
    visibilityScore: 8,
    isDigital: false,
    isActive: true,
    createdAt: "2023-11-01T12:00:00Z",
    imageUrl: "https://picsum.photos/seed/kumasi1/600/400",
  },
  {
    id: "bb-kum-002",
    title: "KNUST Junction Wall Space",
    type: "Wall",
    size: "10m x 10m",
    regionId: "2",
    city: "Kumasi",
    address: "Building facing KNUST Junction",
    latitude: 6.6732,
    longitude: -1.5654,
    pricePerMonth: 6500,
    trafficEstimate: 120000,
    visibilityScore: 7,
    isDigital: false,
    isActive: true,
    createdAt: "2023-08-20T12:00:00Z",
    imageUrl: "https://picsum.photos/seed/kumasi2/600/400",
  },
  {
    id: "bb-tak-001",
    title: "Takoradi Market Circle LED",
    type: "Digital LED",
    size: "8m x 4m",
    regionId: "3",
    city: "Takoradi",
    address: "Market Circle, Central Takoradi",
    latitude: 4.893,
    longitude: -1.7554,
    pricePerMonth: 8000,
    trafficEstimate: 90000,
    visibilityScore: 9,
    isDigital: true,
    isActive: true,
    createdAt: "2024-01-10T12:00:00Z",
    imageUrl: "https://picsum.photos/seed/takoradi1/600/400",
  },
  {
    id: "bb-tam-001",
    title: "Tamale Central Unipole",
    type: "Unipole",
    size: "15m x 10m",
    regionId: "4",
    city: "Tamale",
    address: "Main road into Tamale city center",
    latitude: 9.407,
    longitude: -0.8537,
    pricePerMonth: 5000,
    trafficEstimate: 70000,
    visibilityScore: 7,
    isDigital: false,
    isActive: true,
    createdAt: "2023-12-05T12:00:00Z",
    imageUrl: "https://picsum.photos/seed/tamale1/600/400",
  },
];

export const vendors: Vendor[] = [
  {
    id: "ven-001",
    name: "Apex Prints",
    serviceType: "PRINTING",
    region: "Greater Accra",
    phone: "024 123 4567",
    rating: 4.8,
    verified: true,
    imageUrl: "https://picsum.photos/seed/vendorprint/400/300",
  },
  {
    id: "ven-002",
    name: "Creative Spark Designs",
    serviceType: "DESIGN",
    region: "Ashanti",
    phone: "020 987 6543",
    rating: 4.9,
    verified: true,
    imageUrl: "https://picsum.photos/seed/vendordesign/400/300",
  },
  {
    id: "ven-003",
    name: "HighRise Installations",
    serviceType: "INSTALLATION",
    region: "Greater Accra",
    phone: "055 555 8888",
    rating: 4.7,
    verified: true,
    imageUrl: "https://picsum.photos/seed/vendorinstall/400/300",
  },
];
